# Trivy ignore file for accepted security risks
# https://trivy.dev/docs/latest/configuration/filtering/

misconfigurations:
  # Magento CronJobs - require writable filesystem for PHP cache/sessions
  # Risk accepted: containers run as non-root with dropped capabilities
  - id: AVD-KSV-0014
    paths:
      - apps/base/business-system/magento-makergroup/auntalma/cronjob.yaml
      - apps/base/business-system/magento-makergroup/auntalma/redis-statefulset.yaml
      - apps/base/business-system/magento-makergroup/hayden/cronjob.yaml
    statement: |
      Magento requires writable filesystem for PHP opcache, session storage,
      and generated code. Containers run as non-root with dropped capabilities.

  # Multus CNI - ClusterRole needs full access to k8s.cni.cncf.io resources
  # Risk accepted: CNI plugin requires this for network management
  - id: AVD-KSV-0046
    paths:
      - apps/base/network-system/multus/app/rbac.yaml
    statement: |
      Multus CNI requires wildcard RBAC access to manage network-attachment-definitions
      and related CRDs for container network interface management.

  # Dovecot IMAP proxy - config uses %w variable substitution, not actual secrets
  # Risk accepted: imapc_password=%w passes client credentials at runtime
  - id: AVD-KSV-0109
    paths:
      - apps/base/business-system/dovecot/app/configmap.yaml
    statement: |
      Dovecot imapc configuration uses %w variable substitution for runtime
      password passthrough to Migadu IMAP. No actual secrets are stored in the
      ConfigMap - credentials are provided by users at login time.

  # Dovecot IMAP proxy - needs writable filesystem for internal state
  # Risk accepted: runs with dropped capabilities, no privilege escalation
  - id: AVD-KSV-0014
    paths:
      - apps/base/business-system/dovecot/app/deployment.yaml
    statement: |
      Dovecot requires writable filesystem for /var/lib/dovecot state directory.
      Container runs with dropped capabilities and no privilege escalation.
