# TODO: Encrypt with SOPS after setting credentials
# sops -e -i kubernetes/apps/base/observability/ipmi-exporter/app/secret.enc.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ipmi-exporter-secrets
stringData:
  IPMI_USER: ENC[AES256_GCM,data:3sDHVW4=,iv:Jgxq4jj3DK2Cz1BQSBmmUZgvHY9x0fCHSNSk7oHwlbs=,tag:KftpKNdgYr2I9UgVyQADTQ==,type:str]
  IPMI_PASS: ENC[AES256_GCM,data:jzULJoOk9yc=,iv:mfJXeKLSOT7/P+NCheAKFfhy5xpT0fY1K1b4cJH+tqE=,tag:S7FxCaIJyxzLtVJvwmV+mQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaK29Zb1ZjUTE2MTRlUkx0
        dDhzVytDUDQycVJIMkhIZmExa3lqZU80QTFvClBGYUcrRnF2YWNYeG1HalhOa2xr
        eC9zUkxrWVJVWGpNcTRBcUpkM01CMDQKLS0tIGQ3bWlUTFpXV2hFclBjV3JyRzlD
        N1FHZU5ZOG9TdXZFRm8rSFpZcEVoNDQK4bURKK4+LGAosfZzINZSnqJ6BaaPovRC
        iTw96mQUSvGTv+aGT8fGcIdcOQmKbOls/91/sJJ/rPA+yUqLSe+YBA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-22T04:11:08Z"
  mac: ENC[AES256_GCM,data:H8H73IQ9upKT2Epy+eItd1HrY/7zPRirItnpXglAbLJt+1fk4DwBAJLNE8qkt14NogO7T5OokgqAbOPTbDFxZzvJGR1IPg5J5DcDnBdl8SH16mxJkBFVCrQhKsSobp22u3ccjeRstq4qMoWvu5s43kwok7XBhvAL5WFWkWUNiSg=,iv:35UZRtaeU1yoaLuKsg8TUJcCL+bjdqv7Pe6U9VddPMA=,tag:pODr0rxybG6tDI/MrpCwDQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
