---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: opensearch-charts
  namespace: business-system
spec:
  interval: 30m
  url: https://opensearch-project.github.io/helm-charts/
