---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: odoo-pg-pooler
  namespace: business-system
spec:
  cluster:
    name: odoo-pg
  instances: 3
  type: rw
  template:
    spec:
      containers: []
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              cnpg.io/poolerName: odoo-pg-pooler
  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "200"
      default_pool_size: "25"
      min_pool_size: "5"
      reserve_pool_size: "5"
      reserve_pool_timeout: "3"
      server_idle_timeout: "60"
      server_connect_timeout: "5"
      server_login_retry: "1"
      dns_max_ttl: "5"
