# TODO: Encrypt with SOPS after setting the community string
# sops -e -i kubernetes/apps/base/observability/snmp-exporter/app/secret.enc.yaml
apiVersion: v1
kind: Secret
metadata:
  name: snmp-exporter-secrets
stringData:
  SNMP_COMMUNITY: ENC[AES256_GCM,data:wzRLJj4V,iv:5GjteoRICsQaH1QFy6droen9joZktuw7NoY8z6L+XdI=,tag:/vozcUXGALqQh+GBGwf/WQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcDJZL0RpQXNTdGJPT1py
        Wk1aVlpHVElvOTlkSmlLOCs5UVVDelErVlZ3Ck0wcFV4cGxIa3pWaGRHT2QzbFkz
        VFo5VVFzT2hNQTZkbVpWYlBmN09ZZlkKLS0tIDZhcGE4YlMyZlVoZFlTU0h2WldL
        TWcrL3ZXTStpWkdVQlUzeFVIZ0JZcTAKY4KL69x5WkF+8PdJKaS2w6sFt1JMXU+2
        4WxPTXUv9uZtVhedHR0G5GjRJPLzU2INpFI2l0lyGh5SME3fckYFtg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-22T04:11:08Z"
  mac: ENC[AES256_GCM,data:MtLkfu4sZX3sN69VhktG9ljQ5GBXvuulv3b1gh3XRISqgjZINxKupnPTELaW6CilDL4XWUnKcov2hUi2SCHu5hv/Xvg1SKb7pjuj2Ils+9PplPzaMRLMJDCUrHgOQI5JZQF+6Hpr0MF2ibzIP2BK31rWBQfxVbAmShJHTySMOOs=,iv:aOfAl6VgMufAgVB9/NkKcaCu67EZ1ST7c9+W6mvDepY=,tag:12vCvdNFHHYGy7Eu50zenQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
