# TODO: Encrypt with SOPS after setting credentials
# Create a LOCAL-ONLY account on your UDM-Pro for UnPoller (not your admin account)
# UDM-Pro: Settings > Admins > Add Admin > Local Only, Read-Only role
# sops -e -i kubernetes/apps/base/observability/unpoller/app/secret.enc.yaml
apiVersion: v1
kind: Secret
metadata:
  name: unpoller-secrets
stringData:
  UP_UNIFI_DEFAULT_USER: ENC[AES256_GCM,data:mZu4nMjYi6Zl4Og74SFk6jA=,iv:+/Lz/b2RTGOXh6uY1byFfNvplXihWRAyG+e8kXSylCw=,tag:BlMXPMfTcnEccXdpnDoprw==,type:str]
  UP_UNIFI_DEFAULT_PASS: ENC[AES256_GCM,data:mmd8BEE0nGa7frZwLy0=,iv:cLpcZFeBpRXfm3n2V24+eEMGNkc3BQVpfV/QZIL01Tw=,tag:CuKN8ZroK4UB9v31SVshJw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NGpMNEh4a3R0V2h2R0VD
        cEl5aTVvbjZjemU5SC9wNlZNSGFEUlljK1VBCjBiS3Vqek55K25OUU8rQU4yclBD
        ZXJrbDU1bUlNNHljcjFaSjZ4RVN1L3MKLS0tIGJsWXBEQnNMdkJiWDBpZisxUkhU
        blJ4TjAxOU5yNHEyWmRlRGw2dnBjY0kKtCCdlJHhm5k+QFP8JIFzBvN9Z/Vcc8BT
        X8djuH8kQ/FM6gDfVnEoZyh5llfkBv4m+YZR7Qw2crwSU0ZUkhbXyQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-26T10:22:10Z"
  mac: ENC[AES256_GCM,data:ifJPNaK0cfWMA6t00d5ojWESRGTIraGMRXIdP1APtYVdtccK7niiSlbgPfWRBzWNuMBdWNYTAbEdf5crDkimEqYvmke2uLsGvRCNkjoyxiwpdT/2fR7N1s3nExopN36BJzbAKFl28geWPkCvXpJOxWn+3UKexS6jiZLytXjfiu0=,iv:RrEwuCEv1f8qOW7r2wjFDEf5WdJTQn2kz0t+JhB+8DE=,tag:XahsO1Vsbd0tkgoOyNYQ4A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
