# TODO: Encrypt with SOPS after setting credentials
# Create a LOCAL-ONLY account on your UDM-Pro for UnPoller (not your admin account)
# UDM-Pro: Settings > Admins > Add Admin > Local Only, Read-Only role
# sops -e -i kubernetes/apps/base/observability/unpoller/app/secret.enc.yaml
apiVersion: v1
kind: Secret
metadata:
  name: unpoller-secrets
stringData:
  UP_UNIFI_DEFAULT_USER: ENC[AES256_GCM,data:yScWvy/UxXg=,iv:yKGlTO95CSPXOrJca/2lewRPf4Tsdm1xwQVkWKboXOs=,tag:pHMA+E8tDv0Dzjd1lHER/w==,type:str]
  UP_UNIFI_DEFAULT_PASS: ENC[AES256_GCM,data:CDTtsLYKIjI=,iv:zAuhljPoR7pgjpWKjfRUrZ2mM5iZ/W+xIU9vKlpwsp4=,tag:yWuziI5scEXYd4x+E8ZgrA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NGpMNEh4a3R0V2h2R0VD
        cEl5aTVvbjZjemU5SC9wNlZNSGFEUlljK1VBCjBiS3Vqek55K25OUU8rQU4yclBD
        ZXJrbDU1bUlNNHljcjFaSjZ4RVN1L3MKLS0tIGJsWXBEQnNMdkJiWDBpZisxUkhU
        blJ4TjAxOU5yNHEyWmRlRGw2dnBjY0kKtCCdlJHhm5k+QFP8JIFzBvN9Z/Vcc8BT
        X8djuH8kQ/FM6gDfVnEoZyh5llfkBv4m+YZR7Qw2crwSU0ZUkhbXyQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-22T04:11:08Z"
  mac: ENC[AES256_GCM,data:8iZVcR8mj2gJutGIQ9KyWGPHzqc6p5yLvlgsNVe7XUbbDdqwsvcyeZ5aDhcE1Lvxhq6GXRa2NifJw7YCLhwxjYIkp0pvJIHmFckrOuFQan+fbt02ka6fFGVfcLq4awrK0JpcEpAZNKpPNt2CWdANXpzXnwv73gC3qDk7UAb6wGQ=,iv:xixSa5gdwJfanfzaEB233dmS7HpulFTn4h5g7OctQG0=,tag:1i8vcMumVTysnEbOvpDaTQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
